#!/bin/sh
PASS=true

# format all files
go fmt ./...

# vet all files
go vet ./...
if [[ $? != 0 ]]; then
  PASS=false
fi

# run all tests
go test ./...
if [[ $? == 1 ]]; then
  PASS=false
fi

# lint all files
golint "-set_exit_status" ./...
if [[ $? == 1 ]]; then
  PASS=false
fi

if ! $PASS; then
  printf "Commit failed by pre-commit checks!\n"
  exit 1
fi

exit 0
